import logging
import json
from typing import Dict, Any
from backend.core.interfaces import BaseAgent
from backend.providers.llm_provider import OllamaProvider
from backend.prompts.storyboard import STORYBOARD_SYSTEM_PROMPT, generate_storyboard_user_prompt

logger = logging.getLogger(__name__)

class StoryboardAgent(BaseAgent):
    """
    Agent responsible for breaking a lesson into a scene-by-scene storyboard JSON.
    """
    def __init__(self):
        self.llm_provider = OllamaProvider()

    async def process(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expects payload: {
            "lesson_id": "...", 
            "lesson_title": "...", 
            "lesson_content": {...} # Generated by LessonAgent
        }
        Returns: {"lesson_id": "...", "storyboard": {...}}
        """
        lesson_id = payload.get("lesson_id")
        title = payload.get("lesson_title")
        content = payload.get("lesson_content")
        
        if not content:
            raise ValueError("StoryboardAgent requires 'lesson_content' in payload.")
            
        logger.info(f"StoryboardAgent generating script for lesson: {title}")
        
        content_str = json.dumps(content, indent=2)
        user_prompt = generate_storyboard_user_prompt(content_str)
        
        storyboard_json = await self.llm_provider.generate_json(
            prompt=user_prompt,
            system_prompt=STORYBOARD_SYSTEM_PROMPT
        )
        
        logger.info(f"Storyboard successfully generated for lesson: {title}")
        
        return {
            "status": "success",
            "lesson_id": lesson_id,
            "lesson_title": title,
            "storyboard": storyboard_json
        }
