import logging
import os
import edge_tts
from typing import Dict, Any
from backend.core.interfaces import BaseAgent
from backend.core.config import settings
from .kinetic_ui import KineticUI

# Note: moviepy v2.x import
try:
    from moviepy import ImageClip, AudioFileClip, concatenate_videoclips
except ImportError:
    logging.warning("moviepy not installed. VideoAgent will fail.")

logger = logging.getLogger(__name__)

class VideoAgent(BaseAgent):
    """
    Agent responsible for generating the final video from the Storyboard JSON.
    """
    def __init__(self):
        self.output_dir = os.path.join(settings.UPLOAD_DIR, "videos")
        os.makedirs(self.output_dir, exist_ok=True)
        self.kinetic_ui = KineticUI(output_dir=os.path.join(self.output_dir, "frames"))
        
        # Edge TTS default voice
        self.voice = "en-US-ChristopherNeural" 

    async def _generate_audio(self, text: str, output_path: str):
        communicate = edge_tts.Communicate(text, self.voice)
        await communicate.save(output_path)

    async def process(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Expects payload: {
            "lesson_id": "...", 
            "lesson_title": "...", 
            "storyboard": {"scenes": [...]} # Generated by StoryboardAgent
        }
        Returns: {"lesson_id": "...", "video_path": "..."}
        """
        lesson_id = payload.get("lesson_id")
        title = payload.get("lesson_title")
        storyboard = payload.get("storyboard")
        
        if not storyboard or "scenes" not in storyboard:
            raise ValueError("VideoAgent requires 'storyboard' with 'scenes' in payload.")
            
        logger.info(f"VideoAgent starting compilation for lesson: {title}")
        
        video_clips = []
        
        for idx, scene in enumerate(storyboard["scenes"]):
            scene_id = scene.get("scene_id", idx)
            narration = scene.get("narration", "")
            keyword = scene.get("keyword", "")
            symbol = scene.get("symbol", "")
            
            logger.info(f"Processing scene {scene_id}...")
            
            # 1. Generate Audio
            audio_path = os.path.join(self.output_dir, f"audio_{scene_id}.mp3")
            await self._generate_audio(narration, audio_path)
            
            # 2. Generate Image Frame
            frame_path = self.kinetic_ui.generate_frame(keyword, symbol, str(scene_id))
            
            # 3. Create Clip
            # Load audio to get duration
            audio_clip = AudioFileClip(audio_path)
            # Create image clip lasting the duration of the audio
            img_clip = ImageClip(frame_path).with_duration(audio_clip.duration)
            # Set audio
            video_clip = img_clip.with_audio(audio_clip)
            
            video_clips.append(video_clip)
            
        # 4. Composite final video
        final_video = concatenate_videoclips(video_clips, method="compose")
        final_path = os.path.join(self.output_dir, f"lesson_{lesson_id}_video.mp4")
        
        logger.info("Writing final video file (this may take a moment)...")
        # Write to file (24fps is sufficient for kinetic UI)
        final_video.write_videofile(final_path, fps=24, logger=None)
        
        # Cleanup clips from memory
        for clip in video_clips:
            clip.close()
        final_video.close()
        
        logger.info(f"Video compiled successfully at {final_path}")
        
        return {
            "status": "success",
            "lesson_id": lesson_id,
            "lesson_title": title,
            "video_path": final_path
        }
